/* ── Interface strings (V3, stage 1) ─────────────────────────────────
   The chrome — navigation, buttons, labels, dialogs — separately from
   the readings. The two are translated on different schedules: the
   interface switches to Russian as soon as these exist, while the
   readings keep falling back to English until content.ru.js is filled
   in. That staging is the point; see i18n.js.

   KEYS ARE NAMESPACED BY SCREEN (`auth.*`, `menu.*`, `display.*`) so a
   string's home is obvious from its name, and so a screen can be worked
   through in one pass without hunting.

   EVERY KEY MUST EXIST IN `en`. English is the fallback, so a key
   missing there has nothing to fall back to and would render as its own
   key name. A key missing from `ru` simply shows English — which is
   exactly stage 1's behaviour for anything not yet done.

   Interpolation is `{name}`: t("record.saved", { date: "2 October" }). */

export const STRINGS = {
  en: {
    /* ── Boot ── */
    "boot.loading": "Loading the ephemeris",
    "boot.failed": "The sky didn’t finish loading.",
    "boot.retry": "Try again",
    "boot.detail": "Technical detail",
    "boot.storage": "Your browser is blocking local storage, so check-ins can’t be saved on this device.",

    /* ── Auth ── */
    "auth.tablist": "Log in or sign up",
    "auth.login": "Log in",
    "auth.signup": "Sign up",
    "auth.welcome": "Welcome back",
    "auth.create": "Create your account",
    "auth.lede": "The moon, read through your own chart.",
    "auth.email": "Email",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Password",
    "auth.confirm": "Confirm password",
    "auth.showPassword": "Show password",
    "auth.hidePassword": "Hide password",
    "auth.forgot": "Forgot password?",
    "auth.createBtn": "Create account",
    "auth.reset": "Reset your password",
    "auth.resetLede": "We’ll email you a link to set a new one.",
    "auth.sendReset": "Send reset link",
    "auth.checkInbox": "Check your inbox",
    "auth.sentConfirm": "We’ve sent a confirmation link to {email}. Click it to finish setting up your account.",
    "auth.sentReset": "We’ve sent a password reset link to {email}.",
    "auth.badPassword": "That password doesn’t match this email. Try again, or reset it below.",

    /* ── Header and menu ── */
    "app.name": "Lunar Tracker",
    "menu.location": "Location",
    "menu.display": "Display",
    "menu.data": "Your data",
    "menu.about": "About",
    "menu.chart": "Your chart",
    "menu.signOut": "Sign out",
    "menu.checkin": "Check-in",
    "menu.checkedIn": "Checked in ✓",

    /* ── Date navigation ── */
    "date.chooseDate": "Choose date",
    "date.prev": "Previous day",
    "date.next": "Next day",
    "date.today": "Today",
    "date.history": "Open history calendar",
    "date.backToToday": "Back to today",
    "date.backToDaily": "Back to daily view",

    /* ── Zodiac toggle ── */
    "zodiac.group": "Zodiac system",
    "zodiac.tropical": "Tropical",
    "zodiac.sidereal": "Sidereal",

    /* ── Display dialog ── */
    "display.title": "Display",
    "display.language": "Language",
    "display.languageHelp": "Readings and interface. Your check-ins are unaffected — they store codes, not words, so they read correctly in either language.",
    "display.options": "Display options",
    "display.affirmations": "Show New Moon affirmations",
    "display.affirmationsHelp": "Affirmations for the natal house of the most recent New Moon, shown for 28 days. Applies immediately.",
    "display.transitions": "Show transition times",
    "display.transitionsHelp": "When the Moon changes sign or house during a day, note the time it happens.",
    "display.bothReadings": "Show both readings on transition days",
    "display.bothReadingsHelp": "On today, also show the reading the Moon moves into later, alongside the current one. Past and future days always show both.",
    "display.recordCard": "Show your check-in on the daily view",
    "display.recordCardHelp": "The saved check-in card, shown on days you checked in. Turning it off hides the card — your check-ins are kept either way.",

    /* ── Your data dialog ── */
    "data.title": "Your data",
    "data.export": "Export",
    "data.exportHelp": "Everything on your account — your chart, every check-in with the sky it was saved under, and your ritual marks — as a single JSON file. Yours to keep, readable without this app.",
    "data.download": "Download my data",
    "data.collecting": "Collecting…",
    "data.exportFailed": "Couldn’t build the export just now. Check your connection and try again.",
    "data.deleteTitle": "Delete account",
    "data.deleteHelp": "This deletes your account and everything in it: your chart, all your check-ins, and every ritual mark. It happens immediately and cannot be undone — there is no copy for us to restore from. Download your data first if you want to keep it.",
    "data.deleteStart": "Delete my account",
    "data.deleteConfirmLabel": "Type DELETE to confirm",
    "data.deleteGo": "Delete everything",
    "data.deleting": "Deleting…",
    "data.deleteFailed": "Couldn’t delete the account. Nothing was removed — try again, or get in touch.",
    "data.cancel": "Cancel",

    /* ── About ── */
    "about.title": "About",
    "about.engine": "Positions computed with the Swiss Ephemeris, in your browser.",
    "about.licence": "This app is free software under the AGPL-3.0:",
    "about.source": "read or download the source",

    "sign.moon_word": "Moon",

    /* ── Errors and states ── */
    "err.chartUnreachable": "Couldn’t load your chart.",
    "err.chartUnreachableBody": "We reached your account but not your chart, so we don’t know whether you’ve set one up. Nothing has been changed.",
    "err.chartCompute": "Couldn’t compute the chart: {reason}",
    "geo.noResults": "No results — try the manual coordinates below",
    "geo.busy": "The place search is busy — wait a moment and try again.",
    "geo.unavailable": "The place search is unavailable right now (error {status}). Try again shortly.",
    "geo.unreachable": "Couldn’t reach the place search. Check your connection and try again.",
    "geo.preferRetry": "Your birthplace is almost certainly listed — prefer retrying over entering coordinates by hand.",
    "geo.selected": "Selected: {place}",
    "geo.approximate": "— entered as coordinates, so this location is approximate. Search for the place name if you can; it moves the house cusps.",
    "ritual.newMoonExact": "New Moon exact at {time} — wishes count from then.",
    "ritual.newMoonOpens": "The New Moon is exact at {time} — the wishing window opens then.",
    "data.downloaded": "Downloaded — {checkIns} and {rituals}.",
    "data.nCheckIns.one": "{n} check-in",
    "data.nCheckIns.other": "{n} check-ins",
    "data.nRituals.one": "{n} ritual mark",
    "data.nRituals.other": "{n} ritual marks",

    /* ── Transit panel ── */
    "transit.orb": "(orb {orb}°)",
    "transit.noneToday": "No natal conjunctions today",
    "transit.noProfile": "Create a natal profile to see house placements and conjunctions.",
    "transit.createProfile": "Create profile",
    "transit.badData": "This profile’s birth data could not be interpreted ({reason}). Edit the profile to fix it.",
    "transit.approx": "positions approximate (no birth time)",
    "transit.addTime": "Add a birth time to see house placements and angle conjunctions.",
    "reading.none": "No readings for this day.",

    /* ── Natal points ── */
    "point.Sun": "Natal Sun",
    "point.Moon": "Natal Moon",
    "point.Mercury": "Natal Mercury",
    "point.Venus": "Natal Venus",
    "point.Mars": "Natal Mars",
    "point.Jupiter": "Natal Jupiter",
    "point.Saturn": "Natal Saturn",
    "point.Uranus": "Natal Uranus",
    "point.Neptune": "Natal Neptune",
    "point.Pluto": "Natal Pluto",
    "point.NorthNode": "North Node",
    "point.SouthNode": "South Node",
    "point.Chiron": "Natal Chiron",
    "point.Ascendant": "Ascendant",
    "point.Descendant": "Descendant",
    "point.Midheaven": "Midheaven",
    "point.ImumCoeli": "Imum Coeli",

    /* ── Moon card ── */
    "moon.illuminated": "{pct}% illuminated",
    "moon.exactAt": "Exact at {time}",
    "moon.next": "Next · {events}",
    "moon.moonrise": "Moonrise",
    "moon.moonset": "Moonset",
    "moon.sunrise": "Sunrise",
    "moon.sunset": "Sunset",
    "moon.thatDaysMoon": "That day’s moon",
    "moon.openReading": "Open this day’s reading ›",
    "moon.affirmations": "New Moon affirmations",
    "moon.openRitual": "Open the ritual ›",

    /* ── Eclipses ── */
    "eclipse.notVisible": "Greatest eclipse {time} · not visible from {where}",
    "eclipse.sunBelow": " — the Sun is below the horizon",
    "eclipse.moonBelow": " — the Moon is below the horizon",
    "eclipse.solarMax": "Maximum {time} · {pct}% of the Sun covered from {where}",
    "eclipse.lunarMax": "Greatest {time} · {how}, visible from {where}",
    "eclipse.fullShadow": "the Moon fully in shadow",
    "eclipse.partShadow": "{pct}% of the Moon in shadow",
    "eclipse.penumbral": "penumbral only — a faint shading",

    /* ── Phases, extra ── */
    "phase.waxing_quarter": "Waxing Quarter Moon",
    "phase.waning_quarter": "Waning Quarter Moon",

    /* ── Boot ── */
    "boot.note": "584 KB engine · 2 MB sky data. First visit only — it is cached after that.",
    "boot.failedBody": "The download was interrupted, so the app can’t calculate today yet. Nothing is lost — try again when you have a steadier connection.",

    /* ── Menu, extra ── */
    "menu.profile": "Profile",
    "menu.history": "History",

    /* ── Footer ── */
    "footer.all": "Computed in-browser with Swiss Ephemeris · Houses: Placidus (Tropical), Whole Sign (Sidereal) · Place search © OpenStreetMap contributors",
    "footer.computed": "Computed in-browser with Swiss Ephemeris",
    "footer.houses": "Houses: Placidus (Tropical), Whole Sign (Sidereal)",
    "footer.places": "Place search © OpenStreetMap contributors",

    /* ── Rituals ── */
    "ritual.notDone": "Not done",
    "ritual.doneMark": "Done ✓",
    "ritual.markDone": "Mark as done",
    "ritual.new_moon_wishing": "New Moon wishing ritual",
    "ritual.full_moon_forgiveness": "Full Moon Forgiveness Ceremony",
    "ritual.full_moon_gratitude": "Entering a State of Gratitude",
    "ritual.newMoonTitle": "New Moon Ritual",
    "ritual.fullMoonTitle": "Full Moon Rituals",

    /* ── Data dialog, markup ── */
    "data.deleteHelpHtml": "This deletes your account and everything in it: your chart, all your check-ins, and every ritual mark. It happens immediately and <strong>cannot be undone</strong> — there is no copy for us to restore from. Download your data first if you want to keep it.",
    "data.confirmLabelHtml": "Type <strong>DELETE</strong> to confirm",
    "about.licenceHtml": "This app is free software under the AGPL-3.0: <a href=\"https://github.com/dakusuyoga/Lunar_Tracker_App\" target=\"_blank\" rel=\"noopener noreferrer\">read or download the source</a>.",

    /* ── Zodiac signs ──
       Two forms, because Russian needs them: `sign.*` is the name on its
       own ("Телец"), `signIn.*` the form after "Луна в" ("в Тельце") —
       the prepositional case. English repeats itself here, and that is
       the point: the call sites stay identical in both languages. */
    "sign.aries": "Aries",
    "sign.taurus": "Taurus",
    "sign.gemini": "Gemini",
    "sign.cancer": "Cancer",
    "sign.leo": "Leo",
    "sign.virgo": "Virgo",
    "sign.libra": "Libra",
    "sign.scorpio": "Scorpio",
    "sign.sagittarius": "Sagittarius",
    "sign.capricorn": "Capricorn",
    "sign.aquarius": "Aquarius",
    "sign.pisces": "Pisces",

    "signIn.aries": "Aries",
    "signIn.taurus": "Taurus",
    "signIn.gemini": "Gemini",
    "signIn.cancer": "Cancer",
    "signIn.leo": "Leo",
    "signIn.virgo": "Virgo",
    "signIn.libra": "Libra",
    "signIn.scorpio": "Scorpio",
    "signIn.sagittarius": "Sagittarius",
    "signIn.capricorn": "Capricorn",
    "signIn.aquarius": "Aquarius",
    "signIn.pisces": "Pisces",

    /* ── Phases ── */
    "phase.new": "New Moon",
    "phase.waxing_crescent": "Waxing Crescent",
    "phase.first_quarter": "First Quarter",
    "phase.waxing_gibbous": "Waxing Gibbous",
    "phase.full": "Full Moon",
    "phase.waning_gibbous": "Waning Gibbous",
    "phase.last_quarter": "Last Quarter",
    "phase.waning_crescent": "Waning Crescent",
    "phase.solarEclipse": "Solar Eclipse",
    "phase.lunarEclipse": "Lunar Eclipse",
    "phase.totalSolar": "Total Solar Eclipse",
    "phase.totalLunar": "Total Lunar Eclipse",

    /* ── Reading headers ── */
    "reading.moonIn": "Moon in {sign} · {deg} · {mode}",
    "reading.signUntil": "{sign} until {time}",
    "reading.signAfter": "{sign} after",
    "reading.signFrom": "{sign} from {time}",
    "reading.since": "since {time}",
    "reading.moonHouse": "Moon transiting the {house} house",
    "reading.houseUntil": "{house} until {time}",
    "reading.houseAfter": "{house} after",
    "reading.houseFrom": "{house} from {time}",
    "reading.houseJoin": ", then the ",
    "reading.moonHouseSpan": "Moon transiting the {span}",
    "reading.moonInYourHouse": "Moon in your {house} house",
    "reading.phaseInYourHouse": "{phase} in your {house} house",
    "reading.moonInSign": "Moon in {sign}",
    "reading.phaseInSign": "{phase} in {sign}",
    "reading.until": "Until {time}",
    "reading.from": "From {time}",
    "reading.house": "{house} house",
    "reading.dailyMoonIn": "Daily Moon in {sign}",

    /* ── First run ── */
    "setup.title": "Let’s set up your chart.",
    "setup.lede": "This is the birth information we read the moon against. You can change it later.",
    "setup.prompt": "Add your birth details to see the moon against your own chart.",
    "setup.cta": "Set up my chart",

    /* ── Chart ── */
    "chart.title": "Your chart",
    "chart.edit": "Edit your chart",
    "chart.checkFields": "Check the highlighted fields.",
    "chart.name": "Profile name",
    "chart.birthDate": "Birth date",
    "chart.birthTime": "Birth time",
    "chart.noTime": "I don’t know my birth time",
    "chart.noTimeHelp": "Without a birth time we can’t calculate houses or angles.",
    "chart.birthPlace": "Birth place",
    "chart.searchCity": "Search for a city…",
    "chart.manual": "Enter coordinates manually",
    "chart.lat": "Latitude",
    "chart.lon": "Longitude",
    "chart.timezone": "Timezone",
    "chart.auto": "(auto)",

    /* ── Location ── */
    "loc.title": "Location",
    "loc.display": "Display location",
    "loc.help": "Drives moonrise/moonset, sunrise/sunset, and the local calendar day. Your natal chart is unaffected.",
    "loc.searchFailed": "Couldn’t reach the place search.",
    "loc.city": "City",
    "loc.searchCity": "Search a city…",
    "loc.current": "Current: {place}",
    "loc.save": "Save location",

    /* ── History ── */
    "history.prevMonth": "Previous month",
    "history.nextMonth": "Next month",
    "history.thisMonth": "This month",
    "history.checkedIn": "Checked in",
    "history.empty": "No check-ins this month.",

    /* ── Saved record screen ── */
    "record.title": "Your check-in — {date}",
    "record.skyAt": "The sky at {time}",
    "record.sign": "Sign",
    "record.house": "House",
    "record.transit": "Transit",
    "record.noConjunctions": "No natal conjunctions",
    "record.rituals": "Rituals",
    "record.done": "Done",
    "record.notDone": "Not done",
    "record.pending": "The sky for this check-in hasn’t been worked out yet — it will fill in next time the app opens with a connection.",
    "record.open": "Open this check-in ›",
    "record.yourCheckin": "Your check-in",

    /* ── Check-in screen ── */
    "checkin.title": "Daily check-in — {date}",
    "checkin.lede": "Log as much or as little as you like. Every field is optional.",
    "checkin.emotions": "Emotions",
    "checkin.body": "Body",
    "checkin.energy": "Energy",
    "checkin.focus": "Focus",
    "checkin.journal": "Journal",
    "checkin.selectAny": "Select any that fit.",
    "checkin.optional": "Optional.",
    "checkin.q.highPleasant": "High energy · pleasant",
    "checkin.q.highUnpleasant": "High energy · unpleasant",
    "checkin.q.lowPleasant": "Low energy · pleasant",
    "checkin.q.lowUnpleasant": "Low energy · unpleasant",
    "checkin.q.neutral": "Neutral",
    "checkin.offScale": "Off the scale",
    "checkin.fluctuatingHelp": "Describes variability through the day, not a level.",
    "checkin.journalPlaceholder": "Anything you want to note about today…",
    "checkin.save": "Save check-in",
    "checkin.saving": "Saving…",
    "checkin.nothingYet": "Nothing selected yet — that’s fine.",
    "checkin.confirmTitle": "Set this down for today?",
    "checkin.confirmHelp": "A saved check-in can’t be changed afterwards — it records how the day actually felt.",
    "checkin.confirmSave": "Save it",
    "checkin.keepEditing": "Keep editing",
    "checkin.saved": "Saved",
    "checkin.savedOffline": "Saved on this device — it will sync when you’re back online",
    "checkin.recordedFor": "Recorded for {date}.",

    /* ── Check-in vocabulary ──
       Keyed by the value STORED in the database, so a check-in saved in
       one language displays correctly in the other — the row holds
       `joyful`, never "Joyful" or "Радостно". applyStrings resolves
       these from [data-field][data-value] directly, so the 45 chips need
       no data-i18n marks of their own. */
    "vocab.anxious_excited": "Anxious – excited",
    "vocab.inspired": "Inspired",
    "vocab.motivated": "Motivated",
    "vocab.powerful": "Powerful",
    "vocab.joyful": "Joyful",
    "vocab.playful": "Playful",
    "vocab.anxious_nervous": "Anxious – nervous",
    "vocab.overwhelmed": "Overwhelmed",
    "vocab.irritable": "Irritable",
    "vocab.frustrated": "Frustrated",
    "vocab.self_doubting": "Self-doubting",
    "vocab.grounded": "Grounded",
    "vocab.attuned": "Attuned",
    "vocab.grateful": "Grateful",
    "vocab.loved": "Loved",
    "vocab.content": "Content",
    "vocab.sad": "Sad",
    "vocab.empty": "Empty",
    "vocab.lonely": "Lonely",
    "vocab.disinterested": "Disinterested",
    "vocab.discouraged": "Discouraged",
    "vocab.neutral": "Neutral",
    "vocab.nostalgic": "Nostalgic",
    "vocab.curious": "Curious",
    "vocab.reflective": "Reflective",
    "vocab.calm": "Calm",
    "vocab.headachey": "Headachey",
    "vocab.nauseous": "Nauseous",
    "vocab.tense": "Tense",
    "vocab.sore": "Sore",
    "vocab.achey": "Achey",
    "vocab.bloated": "Bloated",
    "vocab.horny": "Horny",
    "vocab.restless": "Restless",
    "vocab.heavy": "Heavy",
    "vocab.numb": "Numb",
    "vocab.fatigued": "Fatigued / Exhausted",
    "vocab.low": "Low",
    "vocab.steady": "Steady",
    "vocab.energized": "Energized",
    "vocab.wired": "Wired",
    "vocab.fluctuating": "Fluctuating",
    "vocab.scattered": "Scattered",
    "vocab.present": "Present",
    "vocab.focused": "Focused",

    /* ── Shared buttons ── */
    "btn.done": "Done",
    "btn.save": "Save",
    "btn.cancel": "Cancel",
    "btn.close": "Close",
    "btn.edit": "Edit",
  },

  ru: {
    /* ── Загрузка ── */
    "boot.loading": "Загрузка эфемерид",
    "boot.failed": "Небо не загрузилось до конца.",
    "boot.retry": "Попробовать снова",
    "boot.detail": "Технические подробности",
    "boot.storage": "Браузер блокирует локальное хранилище, поэтому отметки не сохранятся на этом устройстве.",

    /* ── Вход ── */
    "auth.tablist": "Вход или регистрация",
    "auth.login": "Войти",
    "auth.signup": "Регистрация",
    "auth.welcome": "С возвращением",
    "auth.create": "Создайте аккаунт",
    "auth.lede": "Луна, прочитанная через вашу карту.",
    "auth.email": "Эл. почта",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Пароль",
    "auth.confirm": "Подтвердите пароль",
    "auth.showPassword": "Показать пароль",
    "auth.hidePassword": "Скрыть пароль",
    "auth.forgot": "Забыли пароль?",
    "auth.createBtn": "Создать аккаунт",
    "auth.reset": "Сброс пароля",
    "auth.resetLede": "Пришлём на почту ссылку для установки нового.",
    "auth.sendReset": "Отправить ссылку",
    "auth.checkInbox": "Проверьте почту",
    "auth.sentConfirm": "Мы отправили ссылку для подтверждения на {email}. Перейдите по ней, чтобы завершить создание аккаунта.",
    "auth.sentReset": "Мы отправили ссылку для сброса пароля на {email}.",
    "auth.badPassword": "Пароль не подходит к этой почте. Попробуйте ещё раз или сбросьте его ниже.",

    /* ── Шапка и меню ── */
    "app.name": "Lunar Tracker",
    "menu.location": "Местоположение",
    "menu.display": "Отображение",
    "menu.data": "Ваши данные",
    "menu.about": "О приложении",
    "menu.chart": "Ваша карта",
    "menu.signOut": "Выйти",
    "menu.checkin": "Отметиться",
    "menu.checkedIn": "Отмечено ✓",

    /* ── Навигация по дням ── */
    "date.chooseDate": "Выбрать дату",
    "date.prev": "Предыдущий день",
    "date.next": "Следующий день",
    "date.today": "Сегодня",
    "date.history": "Открыть календарь",
    "date.backToToday": "Назад к сегодня",
    "date.backToDaily": "Назад к дневному виду",

    /* ── Зодиак ── */
    "zodiac.group": "Система зодиака",
    "zodiac.tropical": "Тропический",
    "zodiac.sidereal": "Сидерический",

    /* ── Отображение ── */
    "display.title": "Отображение",
    "display.language": "Язык",
    "display.languageHelp": "Тексты и интерфейс. На ваши отметки это не влияет — в них хранятся коды, а не слова, поэтому они правильно читаются на любом языке.",
    "display.options": "Параметры отображения",
    "display.affirmations": "Показывать аффирмации новолуния",
    "display.affirmationsHelp": "Аффирмации для натального дома последнего новолуния, показываются 28 дней. Применяется сразу.",
    "display.transitions": "Показывать время переходов",
    "display.transitionsHelp": "Когда Луна в течение дня меняет знак или дом, отмечать время перехода.",
    "display.bothReadings": "Показывать оба текста в дни перехода",
    "display.bothReadingsHelp": "Сегодня показывать и текст, в который Луна перейдёт позже, рядом с текущим. Для прошлых и будущих дней оба показываются всегда.",
    "display.recordCard": "Показывать отметку в дневном виде",
    "display.recordCardHelp": "Карточка сохранённой отметки в дни, когда вы отмечались. Если выключить, карточка скроется — сами отметки сохраняются в любом случае.",

    /* ── Ваши данные ── */
    "data.title": "Ваши данные",
    "data.export": "Экспорт",
    "data.exportHelp": "Всё, что есть в вашем аккаунте — карта, каждая отметка вместе с небом на момент сохранения и отметки о ритуалах — одним файлом JSON. Он остаётся у вас и читается без этого приложения.",
    "data.download": "Скачать мои данные",
    "data.collecting": "Собираем…",
    "data.exportFailed": "Не удалось собрать файл. Проверьте соединение и попробуйте снова.",
    "data.deleteTitle": "Удалить аккаунт",
    "data.deleteHelp": "Это удалит ваш аккаунт и всё, что в нём: карту, все отметки и все отметки о ритуалах. Произойдёт сразу и отменить нельзя — у нас не остаётся копии для восстановления. Если хотите сохранить данные, сначала скачайте их.",
    "data.deleteStart": "Удалить мой аккаунт",
    "data.deleteConfirmLabel": "Введите DELETE для подтверждения",
    "data.deleteGo": "Удалить всё",
    "data.deleting": "Удаляем…",
    "data.deleteFailed": "Не удалось удалить аккаунт. Ничего не удалено — попробуйте снова или напишите нам.",
    "data.cancel": "Отмена",

    /* ── О приложении ── */
    "about.title": "О приложении",
    "about.engine": "Положения рассчитаны по Swiss Ephemeris прямо в вашем браузере.",
    "about.licence": "Это свободное ПО под лицензией AGPL-3.0:",
    "about.source": "посмотреть или скачать исходный код",

    "sign.moon_word": "Луна",

    /* ── Ошибки и состояния ── */
    "err.chartUnreachable": "Не удалось загрузить вашу карту.",
    "err.chartUnreachableBody": "Мы связались с вашим аккаунтом, но не с картой, поэтому не знаем, создана ли она. Ничего не изменено.",
    "err.chartCompute": "Не удалось рассчитать карту: {reason}",
    "geo.noResults": "Ничего не найдено — попробуйте ввести координаты ниже",
    "geo.busy": "Поиск мест занят — подождите немного и попробуйте снова.",
    "geo.unavailable": "Поиск мест сейчас недоступен (ошибка {status}). Попробуйте чуть позже.",
    "geo.unreachable": "Не удалось обратиться к поиску мест. Проверьте соединение и попробуйте снова.",
    "geo.preferRetry": "Ваше место рождения почти наверняка есть в списке — лучше повторить поиск, чем вводить координаты вручную.",
    "geo.selected": "Выбрано: {place}",
    "geo.approximate": "— введено координатами, поэтому место приблизительно. По возможности найдите место по названию: это сдвигает куспиды домов.",
    "ritual.newMoonExact": "Новолуние точно в {time} — желания считаются с этого момента.",
    "ritual.newMoonOpens": "Новолуние точно в {time} — тогда и откроется окно для желаний.",
    "data.downloaded": "Скачано — {checkIns} и {rituals}.",
    "data.nCheckIns.one": "{n} отметка",
    "data.nCheckIns.few": "{n} отметки",
    "data.nCheckIns.many": "{n} отметок",
    "data.nRituals.one": "{n} отметка о ритуале",
    "data.nRituals.few": "{n} отметки о ритуалах",
    "data.nRituals.many": "{n} отметок о ритуалах",

    /* ── Панель транзитов ── */
    "transit.orb": "(орб {orb}°)",
    "transit.noneToday": "Сегодня натальных соединений нет",
    "transit.noProfile": "Создайте натальную карту, чтобы видеть дома и соединения.",
    "transit.createProfile": "Создать карту",
    "transit.badData": "Данные рождения этой карты не удалось прочитать ({reason}). Измените карту, чтобы исправить.",
    "transit.approx": "положения приблизительны (нет времени рождения)",
    "transit.addTime": "Добавьте время рождения, чтобы видеть дома и соединения с углами.",
    "reading.none": "Текстов на этот день нет.",

    /* ── Натальные точки ── */
    "point.Sun": "натальное Солнце",
    "point.Moon": "натальная Луна",
    "point.Mercury": "натальный Меркурий",
    "point.Venus": "натальная Венера",
    "point.Mars": "натальный Марс",
    "point.Jupiter": "натальный Юпитер",
    "point.Saturn": "натальный Сатурн",
    "point.Uranus": "натальный Уран",
    "point.Neptune": "натальный Нептун",
    "point.Pluto": "натальный Плутон",
    "point.NorthNode": "Северный узел",
    "point.SouthNode": "Южный узел",
    "point.Chiron": "натальный Хирон",
    "point.Ascendant": "Асцендент",
    "point.Descendant": "Десцендент",
    "point.Midheaven": "МС (середина неба)",
    "point.ImumCoeli": "IC (глубина неба)",

    /* ── Карточка Луны ── */
    "moon.illuminated": "освещена на {pct}%",
    "moon.exactAt": "Точно в {time}",
    "moon.next": "Далее · {events}",
    "moon.moonrise": "Восход Луны",
    "moon.moonset": "Заход Луны",
    "moon.sunrise": "Восход Солнца",
    "moon.sunset": "Заход Солнца",
    "moon.thatDaysMoon": "Луна того дня",
    "moon.openReading": "Открыть текст этого дня ›",
    "moon.affirmations": "Аффирмации новолуния",
    "moon.openRitual": "Открыть ритуал ›",

    /* ── Затмения ── */
    "eclipse.notVisible": "Максимум затмения в {time} · не видно из {where}",
    "eclipse.sunBelow": " — Солнце под горизонтом",
    "eclipse.moonBelow": " — Луна под горизонтом",
    "eclipse.solarMax": "Максимум в {time} · закрыто {pct}% Солнца, вид из {where}",
    "eclipse.lunarMax": "Максимум в {time} · {how}, видно из {where}",
    "eclipse.fullShadow": "Луна полностью в тени",
    "eclipse.partShadow": "{pct}% Луны в тени",
    "eclipse.penumbral": "только полутеневое — слабое затенение",

    /* ── Фазы, дополнительно ── */
    "phase.waxing_quarter": "Первая четверть",
    "phase.waning_quarter": "Последняя четверть",

    /* ── Загрузка ── */
    "boot.note": "Движок 584 КБ · данные неба 2 МБ. Только при первом визите — дальше берётся из кэша.",
    "boot.failedBody": "Загрузка прервалась, поэтому приложение пока не может рассчитать сегодняшний день. Ничего не потеряно — попробуйте снова при более устойчивом соединении.",

    /* ── Меню, дополнительно ── */
    "menu.profile": "Профиль",
    "menu.history": "История",

    /* ── Подвал ── */
    "footer.all": "Рассчитано в браузере по Swiss Ephemeris · Дома: Плацидус (тропический), цельнознаковые (сидерический) · Поиск мест © участники OpenStreetMap",
    "footer.computed": "Рассчитано в браузере по Swiss Ephemeris",
    "footer.houses": "Дома: Плацидус (тропический), цельнознаковые (сидерический)",
    "footer.places": "Поиск мест © участники OpenStreetMap",

    /* ── Ритуалы ── */
    "ritual.notDone": "Не выполнено",
    "ritual.doneMark": "Выполнено ✓",
    "ritual.markDone": "Отметить как выполненное",
    "ritual.new_moon_wishing": "Ритуал желаний новолуния",
    "ritual.full_moon_forgiveness": "Церемония прощения в полнолуние",
    "ritual.full_moon_gratitude": "Вхождение в состояние благодарности",
    "ritual.newMoonTitle": "Ритуал новолуния",
    "ritual.fullMoonTitle": "Ритуалы полнолуния",

    /* ── Данные, с разметкой ── */
    "data.deleteHelpHtml": "Это удалит ваш аккаунт и всё, что в нём: карту, все отметки и все отметки о ритуалах. Произойдёт сразу и <strong>отменить нельзя</strong> — у нас не остаётся копии для восстановления. Если хотите сохранить данные, сначала скачайте их.",
    "data.confirmLabelHtml": "Введите <strong>DELETE</strong> для подтверждения",
    "about.licenceHtml": "Это свободное ПО под лицензией AGPL-3.0: <a href=\"https://github.com/dakusuyoga/Lunar_Tracker_App\" target=\"_blank\" rel=\"noopener noreferrer\">посмотреть или скачать исходный код</a>.",

    /* ── Знаки зодиака ── */
    "sign.aries": "Овен",
    "sign.taurus": "Телец",
    "sign.gemini": "Близнецы",
    "sign.cancer": "Рак",
    "sign.leo": "Лев",
    "sign.virgo": "Дева",
    "sign.libra": "Весы",
    "sign.scorpio": "Скорпион",
    "sign.sagittarius": "Стрелец",
    "sign.capricorn": "Козерог",
    "sign.aquarius": "Водолей",
    "sign.pisces": "Рыбы",

    "signIn.aries": "Овне",
    "signIn.taurus": "Тельце",
    "signIn.gemini": "Близнецах",
    "signIn.cancer": "Раке",
    "signIn.leo": "Льве",
    "signIn.virgo": "Деве",
    "signIn.libra": "Весах",
    "signIn.scorpio": "Скорпионе",
    "signIn.sagittarius": "Стрельце",
    "signIn.capricorn": "Козероге",
    "signIn.aquarius": "Водолее",
    "signIn.pisces": "Рыбах",

    /* ── Фазы ── */
    "phase.new": "Новолуние",
    "phase.waxing_crescent": "Растущий серп",
    "phase.first_quarter": "Первая четверть",
    "phase.waxing_gibbous": "Растущая Луна",
    "phase.full": "Полнолуние",
    "phase.waning_gibbous": "Убывающая Луна",
    "phase.last_quarter": "Последняя четверть",
    "phase.waning_crescent": "Убывающий серп",
    "phase.solarEclipse": "Солнечное затмение",
    "phase.lunarEclipse": "Лунное затмение",
    "phase.totalSolar": "Полное солнечное затмение",
    "phase.totalLunar": "Полное лунное затмение",

    /* ── Заголовки текстов ── */
    "reading.moonIn": "Луна в {sign} · {deg} · {mode}",
    "reading.signUntil": "{sign} до {time}",
    "reading.signAfter": "{sign} после",
    "reading.signFrom": "{sign} с {time}",
    "reading.since": "с {time}",
    "reading.moonHouse": "Луна проходит {house} дом",
    "reading.houseUntil": "{house} до {time}",
    "reading.houseAfter": "{house} после",
    "reading.houseFrom": "{house} с {time}",
    "reading.houseJoin": ", затем ",
    "reading.moonHouseSpan": "Луна проходит {span}",
    "reading.moonInYourHouse": "Луна в вашем {house} доме",
    "reading.phaseInYourHouse": "{phase} в вашем {house} доме",
    "reading.moonInSign": "Луна в {sign}",
    "reading.phaseInSign": "{phase} в {sign}",
    "reading.until": "До {time}",
    "reading.from": "С {time}",
    "reading.house": "{house} дом",
    "reading.dailyMoonIn": "Луна дня в {sign}",

    /* ── Первый запуск ── */
    "setup.title": "Настроим вашу карту.",
    "setup.lede": "Это данные рождения, относительно которых читается Луна. Их можно изменить позже.",
    "setup.prompt": "Добавьте данные рождения, чтобы видеть Луну относительно вашей карты.",
    "setup.cta": "Настроить карту",

    /* ── Карта ── */
    "chart.title": "Ваша карта",
    "chart.edit": "Изменить карту",
    "chart.checkFields": "Проверьте выделенные поля.",
    "chart.name": "Имя профиля",
    "chart.birthDate": "Дата рождения",
    "chart.birthTime": "Время рождения",
    "chart.noTime": "Не знаю время рождения",
    "chart.noTimeHelp": "Без времени рождения нельзя рассчитать дома и углы.",
    "chart.birthPlace": "Место рождения",
    "chart.searchCity": "Поиск города…",
    "chart.manual": "Ввести координаты вручную",
    "chart.lat": "Широта",
    "chart.lon": "Долгота",
    "chart.timezone": "Часовой пояс",
    "chart.auto": "(авто)",

    /* ── Местоположение ── */
    "loc.title": "Местоположение",
    "loc.display": "Отображаемое место",
    "loc.help": "Определяет восход и заход Луны и Солнца и местный календарный день. На натальную карту не влияет.",
    "loc.searchFailed": "Не удалось обратиться к поиску мест.",
    "loc.city": "Город",
    "loc.searchCity": "Поиск города…",
    "loc.current": "Сейчас: {place}",
    "loc.save": "Сохранить место",

    /* ── Календарь ── */
    "history.prevMonth": "Предыдущий месяц",
    "history.nextMonth": "Следующий месяц",
    "history.thisMonth": "Этот месяц",
    "history.checkedIn": "Отмечено",
    "history.empty": "В этом месяце отметок нет.",

    /* ── Экран сохранённой отметки ── */
    "record.title": "Ваша отметка — {date}",
    "record.skyAt": "Небо в {time}",
    "record.sign": "Знак",
    "record.house": "Дом",
    "record.transit": "Транзит",
    "record.noConjunctions": "Нет натальных соединений",
    "record.rituals": "Ритуалы",
    "record.done": "Выполнено",
    "record.notDone": "Не выполнено",
    "record.pending": "Небо для этой отметки ещё не рассчитано — оно заполнится при следующем открытии приложения со связью.",
    "record.open": "Открыть эту отметку ›",
    "record.yourCheckin": "Ваша отметка",

    /* ── Экран отметки ── */
    "checkin.title": "Отметка за день — {date}",
    "checkin.lede": "Отмечайте столько, сколько хочется. Все поля необязательны.",
    "checkin.emotions": "Эмоции",
    "checkin.body": "Тело",
    "checkin.energy": "Энергия",
    "checkin.focus": "Внимание",
    "checkin.journal": "Дневник",
    "checkin.selectAny": "Выберите всё, что подходит.",
    "checkin.optional": "Необязательно.",
    "checkin.q.highPleasant": "Высокая энергия · приятно",
    "checkin.q.highUnpleasant": "Высокая энергия · неприятно",
    "checkin.q.lowPleasant": "Низкая энергия · приятно",
    "checkin.q.lowUnpleasant": "Низкая энергия · неприятно",
    "checkin.q.neutral": "Нейтрально",
    "checkin.offScale": "Вне шкалы",
    "checkin.fluctuatingHelp": "Описывает колебания в течение дня, а не уровень.",
    "checkin.journalPlaceholder": "Что угодно, что хочется записать о сегодняшнем дне…",
    "checkin.save": "Сохранить отметку",
    "checkin.saving": "Сохраняем…",
    "checkin.nothingYet": "Пока ничего не выбрано — это нормально.",
    "checkin.confirmTitle": "Записать это за сегодня?",
    "checkin.confirmHelp": "Сохранённую отметку потом не изменить — она фиксирует, каким день был на самом деле.",
    "checkin.confirmSave": "Сохранить",
    "checkin.keepEditing": "Продолжить заполнять",
    "checkin.saved": "Сохранено",
    "checkin.savedOffline": "Сохранено на этом устройстве — синхронизируется, когда появится связь",
    "checkin.recordedFor": "Записано за {date}.",

    /* ── Словарь отметок ── */
    "vocab.anxious_excited": "Тревожно-возбуждённо",
    "vocab.inspired": "Вдохновлённо",
    "vocab.motivated": "С мотивацией",
    "vocab.powerful": "Полон сил",
    "vocab.joyful": "Радостно",
    "vocab.playful": "Игриво",
    "vocab.anxious_nervous": "Тревожно-нервно",
    "vocab.overwhelmed": "Перегружен",
    "vocab.irritable": "Раздражённо",
    "vocab.frustrated": "Досадно",
    "vocab.self_doubting": "Сомневаюсь в себе",
    "vocab.grounded": "Устойчиво",
    "vocab.attuned": "В настрое",
    "vocab.grateful": "С благодарностью",
    "vocab.loved": "Любим",
    "vocab.content": "Удовлетворённо",
    "vocab.sad": "Грустно",
    "vocab.empty": "Опустошённо",
    "vocab.lonely": "Одиноко",
    "vocab.disinterested": "Безразлично",
    "vocab.discouraged": "Уныло",
    "vocab.neutral": "Нейтрально",
    "vocab.nostalgic": "Ностальгия",
    "vocab.curious": "Любопытно",
    "vocab.reflective": "Задумчиво",
    "vocab.calm": "Спокойно",
    "vocab.headachey": "Болит голова",
    "vocab.nauseous": "Подташнивает",
    "vocab.tense": "Напряжение",
    "vocab.sore": "Ломота",
    "vocab.achey": "Ноет",
    "vocab.bloated": "Вздутие",
    "vocab.horny": "Возбуждение",
    "vocab.restless": "Беспокойство",
    "vocab.heavy": "Тяжесть",
    "vocab.numb": "Онемение",
    "vocab.fatigued": "Истощение / усталость",
    "vocab.low": "Низкая",
    "vocab.steady": "Ровная",
    "vocab.energized": "Бодрость",
    "vocab.wired": "На взводе",
    "vocab.fluctuating": "Скачет",
    "vocab.scattered": "Рассеянно",
    "vocab.present": "Присутствую",
    "vocab.focused": "Сосредоточенно",

    /* ── Кнопки ── */
    "btn.done": "Готово",
    "btn.save": "Сохранить",
    "btn.cancel": "Отмена",
    "btn.close": "Закрыть",
    "btn.edit": "Изменить",
  },
};
